### ISSUE TITLE
Databases attribute is nested within MySQL users

### ISSUE THREAD

**Issue by dnunez24** [copious-cookbooks/mysql#11]
When working with the Magento 2 cookbook I bumped the version reference to use the MySQL cookbook version `0.4.4` (from `0.4.2`). Provisioning Vagrant then raised an error due to what appears to be the way the MySQL cookbook treats attributes in the following code:

https://github.com/copious-cookbooks/mysql/blob/3cc23fb0fb9ed5bff1ecec11d81915312b27482b/recipes/tables_and_users.rb#L19-L35

```ruby
node['mysql']['users'].each do |user, data|
  ...
  data['databases'].each do |database|
    ...
  end
end
```

This is at odds with the way they're being reference in the Magento 2 cookbook:

https://github.com/copious/cop_magento2_starter/blob/b89a5a21ee5bc06a0bcec1466881070c716266ce/chef/environments/development.rb#L5-L18

The attribute hierarchy where `databases` are nested within `node['mysql']` instead of `node['mysql']['users']` feels more natural since the databases belong to the MySQL server and not really to a user. So perhaps the code could be:

```ruby
node['mysql']['users'].each do |user, data|
  ...
  node['mysql']['databases'].each do |database|
    ...
  end
end
```

**Comment by dnunez24** [comment]
Ah, actually, now I think I see what the intent was. Giving a single user authorization for more than one database? I can see the use case.

**Comment by colby** [comment]
Correct, we needed a way to add one user to multiple databases. See https://github.com/copious-cookbooks/mysql/issues/9
